services:
  school-management-app:
    image: ulumito/school-management-app:latest
    container_name: school-management-app
    environment:
      - DB_URL=jdbc:postgresql://db:5432/schooldb
      - DB_USERNAME=schooluser
      - DB_PASSWORD=schoolpass
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: schooldb
      POSTGRES_USER: schooluser
      POSTGRES_PASSWORD: schoolpass
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U schooluser -d schooldb"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  db-data: