version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Docker Login
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Build Docker Image
          command: docker build -t ulumito/school-management-app:${CIRCLE_SHA1} .
      - run:
          name: Push Docker Image
          command: docker push ulumito/school-management-app:${CIRCLE_SHA1}

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build