version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Docker Login
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Build Docker Image
          command: docker build -t ulumito/school-management-app:latest .
      - run:
          name: Push Docker Image
          command: docker push ulumito/school-management-app:latest
      - run:
          name: Deploy and Notify
          command: |
            ssh -o StrictHostKeyChecking=no ulumito@f804b6569742242f6b859c31f330a772.serveo.net "
            docker pull ulumito/school-management-app:latest &&
            docker-compose down &&
            docker-compose up -d
            "
            echo "Application is available at https://f804b6569742242f6b859c31f330a772.serveo.net"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build